#!/usr/bin/env bash
set -euo pipefail

echo "==> Installing dependencies..."
npm install

echo "==> Running tests..."
npm test

echo "==> Pushing DB schema..."
npm run db:push

echo "==> Seeding database..."
npm run db:seed

echo "==> Building project..."
npm run build

echo "==> Starting application..."
npm run --prefix apps/web start
